# Generated by Django 5.2.13 on 2026-04-25 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('assistant_response', models.TextField()),
                ('weather_info', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('finish_reason', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_title', models.CharField(blank=True, default='', max_length=255)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('travelers', models.PositiveIntegerField(default=1)),
                ('budget_style', models.CharField(blank=True, default='', max_length=30)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('plan_payload', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('finish_reason', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Plan',
                'verbose_name_plural': 'Trip Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
