# Generated by Django 5.2.13 on 2026-04-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_chathistory_tripplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempleGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='temple', max_length=50)),
                ('location_text', models.TextField(blank=True, default='')),
                ('famous_for', models.TextField(blank=True, default='')),
                ('history', models.TextField(blank=True, default='')),
                ('main_deity', models.CharField(blank=True, default='', max_length=255)),
                ('best_time_to_visit', models.CharField(blank=True, default='', max_length=255)),
                ('best_season', models.CharField(blank=True, default='', max_length=120)),
                ('crowd_level', models.CharField(blank=True, default='', max_length=80)),
                ('average_visit_duration', models.CharField(blank=True, default='', max_length=80)),
                ('photography_policy', models.CharField(blank=True, default='', max_length=255)),
                ('dress_code', models.CharField(blank=True, default='', max_length=255)),
                ('entry_fee', models.CharField(blank=True, default='', max_length=120)),
                ('vip_darshan', models.CharField(blank=True, default='', max_length=120)),
                ('nearby_attractions', models.JSONField(blank=True, default=list)),
                ('parking_info', models.CharField(blank=True, default='', max_length=255)),
                ('google_map_keyword', models.CharField(blank=True, default='', max_length=255)),
                ('local_market_food', models.TextField(blank=True, default='')),
                ('timings', models.JSONField(blank=True, default=list)),
                ('important_tips', models.JSONField(blank=True, default=list)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('source_note', models.CharField(blank=True, default='Mathura-Vrindavan Darshan Guide 2026', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Temple Guide',
                'verbose_name_plural': 'Temple Guides',
                'ordering': ['region', 'name'],
            },
        ),
    ]
