"""Structured temple guide data for timetable and detail lookup."""

TEMPLE_GUIDE_DATA = [
    {
        "name": "Banke Bihari Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Goda Vihar, Vrindavan, Uttar Pradesh 281121",
        "famous_for": "Vrindavan ka sabse iconic Banke Bihari darshan aur unique parda system.",
        "history": "Swami Haridas ji se judi parampara; present temple 19th century se major bhakti kendra hai.",
        "main_deity": "Banke Bihari Ji",
        "best_time_to_visit": "Early morning 8:00 AM - 9:00 AM ya weekday evening",
        "best_season": "October to March",
        "crowd_level": "Very High",
        "average_visit_duration": "30-45 minutes",
        "photography_policy": "Not allowed inside temple premises",
        "dress_code": "Modest traditional wear preferred",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Nidhivan", "Radha Raman Temple", "ISKCON Temple"],
        "parking_info": "Limited street parking",
        "google_map_keyword": "Banke Bihari Temple Vrindavan",
        "local_market_food": "Loi Bazaar; peda, kachori, lassi",
        "timings": [
            {"session": "Temple Opening", "timing": "7:45 AM summer / 8:45 AM winter"},
            {"session": "Shringar Aarti", "timing": "7:55 AM summer / 8:45 AM winter"},
            {"session": "Morning Darshan", "timing": "7:45 AM - 12:00 PM summer / 8:45 AM - 1:00 PM winter"},
            {"session": "Rajbhog Aarti", "timing": "11:55 AM"},
            {"session": "Evening Darshan", "timing": "5:30 PM - 9:30 PM summer / 4:30 PM - 8:30 PM winter"},
            {"session": "Shayan Aarti", "timing": "9:25 PM summer / 8:30 PM winter"},
        ],
        "important_tips": [
            "Weekday subah jaldi jaane se crowd thoda manageable hota hai.",
            "Mangala aarti regular days par nahi hoti; mainly Janmashtami special hai.",
            "Mobile silent rakhein aur photo bilkul mat lein.",
        ],
        "aliases": ["Banke Bihari", "Shri Banke Bihari Temple"],
    },
    {
        "name": "Prem Mandir",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Raman Reti, Mathura-Vrindavan Road, Vrindavan",
        "famous_for": "Italian marble architecture, night lighting, fountain show, leela jhankiyan.",
        "history": "Jagadguru Kripalu Ji Maharaj ke vision se 2012 mein public darshan ke liye khula.",
        "main_deity": "Radha Krishna and Sita Ram",
        "best_time_to_visit": "Evening 4:30 PM - 7:30 PM",
        "best_season": "October to March",
        "crowd_level": "Medium-High",
        "average_visit_duration": "1.5 - 2 hours",
        "photography_policy": "Allowed in premises, not in garbhagriha",
        "dress_code": "Modest and clean attire",
        "entry_fee": "Free",
        "vip_darshan": "Not applicable",
        "nearby_attractions": ["ISKCON Temple", "Rangji Temple"],
        "parking_info": "Ample dedicated parking",
        "google_map_keyword": "Prem Mandir Vrindavan",
        "local_market_food": "Temple canteen and affordable satvik food",
        "timings": [
            {"session": "Mangala Aarti", "timing": "5:30 AM"},
            {"session": "Morning Darshan", "timing": "8:30 AM - 12:00 PM"},
            {"session": "Evening Darshan", "timing": "4:30 PM - 8:30 PM"},
            {"session": "Sandhya Aarti", "timing": "7:00 PM"},
            {"session": "Musical Fountain", "timing": "7:30 PM - 8:00 PM summer / 7:00 PM - 7:30 PM winter"},
        ],
        "important_tips": [
            "Evening lighting is the main highlight.",
            "Fountain show ke liye thoda early position lein.",
            "Family aur photo lovers ke liye best temple options mein se ek.",
        ],
        "aliases": ["Prem Mandir Vrindavan", "Prem Mandir Temple"],
    },
    {
        "name": "ISKCON Krishna Balaram Mandir",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Bhaktivedanta Swami Marg, Raman Reti, Vrindavan",
        "famous_for": "Peaceful kirtan atmosphere, Prabhupada samadhi, foreigner-friendly darshan.",
        "history": "Srila Prabhupada ne 1975 mein yeh temple establish kiya.",
        "main_deity": "Krishna Balaram, Radha Shyamsundar, Gaur Nitai",
        "best_time_to_visit": "Mangala Aarti 4:30 AM ya Sandhya Aarti 6:30 PM",
        "best_season": "October to March",
        "crowd_level": "Medium",
        "average_visit_duration": "1 - 1.5 hours",
        "photography_policy": "Not allowed inside temple",
        "dress_code": "Modest, shoulders and legs covered",
        "entry_fee": "Free",
        "vip_darshan": "Not applicable",
        "nearby_attractions": ["Prem Mandir", "Rangji Temple"],
        "parking_info": "Enough parking space",
        "google_map_keyword": "ISKCON Temple Vrindavan",
        "local_market_food": "Govinda's Restaurant; satvik pizza, thali, snacks",
        "timings": [
            {"session": "Temple Opening", "timing": "4:30 AM"},
            {"session": "Mangala Aarti", "timing": "4:30 AM"},
            {"session": "Sringar Darshan", "timing": "7:15 AM"},
            {"session": "Morning Darshan", "timing": "4:30 AM - 12:45 PM"},
            {"session": "Utthapan Aarti", "timing": "4:30 PM"},
            {"session": "Sandhya / Gaura Aarti", "timing": "6:30 PM"},
            {"session": "Shayan Aarti", "timing": "8:30 PM"},
        ],
        "important_tips": [
            "Foreign tourists aur first-timers ke liye very comfortable temple.",
            "Govinda's restaurant ko itinerary mein include kar sakte hain.",
            "Morning kirtan aur evening aarti dono special hote hain.",
        ],
        "aliases": ["ISKCON Temple Vrindavan", "Krishna Balaram Temple", "ISKCON Krishna Balaram Temple"],
    },
    {
        "name": "Radha Raman Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Radha Raman Ghera, near Keshi Ghat, Vrindavan",
        "famous_for": "Self-manifested saligram deity and very deep Gaudiya bhakti atmosphere.",
        "history": "Gopala Bhatta Goswami se judi 16th century parampara.",
        "main_deity": "Radha Raman Ji",
        "best_time_to_visit": "Early morning Mangala Aarti",
        "best_season": "October to March",
        "crowd_level": "Low-Medium",
        "average_visit_duration": "30-45 minutes",
        "photography_policy": "Not allowed",
        "dress_code": "Traditional attire preferred",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Keshi Ghat", "Nidhivan", "Banke Bihari Temple"],
        "parking_info": "Limited due to narrow lanes",
        "google_map_keyword": "Radha Raman Temple Vrindavan",
        "local_market_food": "Small shops nearby; peda and samosa",
        "timings": [
            {"session": "Mangala Aarti", "timing": "4:30 AM - 5:30 AM seasonal"},
            {"session": "Morning Darshan", "timing": "8:00 AM - 12:30 PM"},
            {"session": "Evening Darshan", "timing": "6:00 PM - 8:00 PM"},
            {"session": "Sandhya Aarti", "timing": "At sunset"},
        ],
        "important_tips": [
            "Early morning visit most peaceful hota hai.",
            "No photography, no casual behavior inside.",
            "Keshi Ghat ke saath combine kar sakte hain.",
        ],
        "aliases": ["Shri Radha Raman Temple"],
    },
    {
        "name": "Radha Vallabh Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Radha Vallabh Temple Road, Gotam Nagar, Vrindavan",
        "famous_for": "Radha bhav ki special tradition; crown symbolically represents Radha Rani.",
        "history": "16th century tradition linked to Hit Harivansh Mahaprabhu.",
        "main_deity": "Radha Vallabh Ji",
        "best_time_to_visit": "Sandhya Aarti around 6:30 PM",
        "best_season": "October to March",
        "crowd_level": "Medium",
        "average_visit_duration": "30-40 minutes",
        "photography_policy": "Not allowed",
        "dress_code": "Traditional dress recommended",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Seva Kunj", "Banke Bihari Temple", "Nidhivan"],
        "parking_info": "Limited",
        "google_map_keyword": "Radha Vallabh Temple Vrindavan",
        "local_market_food": "Loi Bazaar; peda, kachori, jalebi",
        "timings": [
            {"session": "Mangala Aarti", "timing": "5:00 AM summer / 5:30 AM winter"},
            {"session": "Morning Darshan", "timing": "7:00 AM - 12:00 PM"},
            {"session": "Utthapan Darshan", "timing": "5:00 PM - 6:00 PM"},
            {"session": "Evening Darshan", "timing": "6:30 PM - 9:00 PM summer / till 8:30 PM winter"},
        ],
        "important_tips": [
            "Sandhya aarti yahan ka main devotional moment hai.",
            "Crowded old lane approach ke liye walking better hoti hai.",
            "Courtyard mein kuch der baithna experience ko deepen karta hai.",
        ],
        "aliases": ["Shri Radha Vallabh Temple"],
    },
    {
        "name": "Radha Damodar Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Near Keshi Ghat, Vrindavan",
        "famous_for": "Giriraj Shila with Krishna footprints and Gaudiya lineage importance.",
        "history": "Jiva Goswami tradition; 16th century se major bhakti center.",
        "main_deity": "Radha Damodar",
        "best_time_to_visit": "Early morning",
        "best_season": "October to March",
        "crowd_level": "Low-Medium",
        "average_visit_duration": "30-45 minutes",
        "photography_policy": "Not allowed",
        "dress_code": "Traditional preferred",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Keshi Ghat", "Radha Raman Temple", "Imlitala"],
        "parking_info": "Very limited",
        "google_map_keyword": "Radha Damodar Temple Vrindavan",
        "local_market_food": "Street food near Keshi Ghat",
        "timings": [
            {"session": "Mangala Aarti", "timing": "4:00 AM summer / 4:30 AM winter"},
            {"session": "Morning Darshan", "timing": "4:00 AM - 12:45 PM summer / 4:30 AM - 12:45 PM winter"},
            {"session": "Rajbhog Aarti", "timing": "12:00 PM - 12:30 PM"},
            {"session": "Evening Darshan", "timing": "4:30 PM - 9:00 PM summer / 4:00 PM - 8:45 PM winter"},
        ],
        "important_tips": [
            "Giriraj Shila darshan miss na karein.",
            "Parikrama tradition ko local devotees se samajhna achha rahega.",
            "Morning slot sabse quiet hota hai.",
        ],
        "aliases": ["Shri Radha Damodar Temple"],
    },
    {
        "name": "Rangji Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Mathura-Vrindavan Marg, Vrindavan",
        "famous_for": "South Indian Dravidian style architecture in Braj.",
        "history": "19th century temple inspired by South Indian Vaishnav tradition.",
        "main_deity": "Sri Ranganath Ji",
        "best_time_to_visit": "Morning or evening aarti",
        "best_season": "October to March",
        "crowd_level": "Medium",
        "average_visit_duration": "45-60 minutes",
        "photography_policy": "Premises allowed, garbhagriha not allowed",
        "dress_code": "Modest attire",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Govind Dev Ji Temple", "ISKCON Temple", "Prem Mandir"],
        "parking_info": "Available",
        "google_map_keyword": "Rangji Temple Vrindavan",
        "local_market_food": "Nearby bazaar and South Indian snacks",
        "timings": [
            {"session": "Mangala Aarti", "timing": "5:30 AM"},
            {"session": "Morning Darshan", "timing": "5:30 AM - 11:00 AM summer / till 12:00 PM winter"},
            {"session": "Bhog Prasad", "timing": "8:00 AM - 9:00 AM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:00 PM summer / 3:00 PM - 9:00 PM winter"},
            {"session": "Sandhya Aarti", "timing": "6:30 PM summer / 6:00 PM winter"},
        ],
        "important_tips": [
            "Architecture dekhne ke liye extra time rakhein.",
            "Photo bahar aur premises mein le sakte hain.",
            "Evening lighting bhi kaafi achhi lagti hai.",
        ],
        "aliases": ["Sri Rangji Temple", "Ranganath Temple Vrindavan"],
    },
    {
        "name": "Govind Dev Ji Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Mathura-Vrindavan Marg, Goda Vihar, Vrindavan",
        "famous_for": "Historic red sandstone architecture and major Krishna heritage site.",
        "history": "Raja Man Singh era ka grand temple; original structure ka ek hissa ab bhi visible hai.",
        "main_deity": "Govind Dev Ji",
        "best_time_to_visit": "Morning 8:00 AM - 10:00 AM",
        "best_season": "October to March",
        "crowd_level": "Medium",
        "average_visit_duration": "30-45 minutes",
        "photography_policy": "Outside photography allowed",
        "dress_code": "Traditional Indian wear preferred",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Rangji Temple", "Radha Raman Temple"],
        "parking_info": "Available",
        "google_map_keyword": "Govind Dev Ji Temple Vrindavan",
        "local_market_food": "Prasad shops and local snacks nearby",
        "timings": [
            {"session": "Mangala Aarti", "timing": "4:30 AM summer / 5:00 AM winter"},
            {"session": "Morning Darshan", "timing": "4:30 AM - 12:30 PM summer / 5:00 AM - 12:30 PM winter"},
            {"session": "Rajbhog Aarti", "timing": "11:45 AM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:30 PM summer / 3:30 PM - 8:30 PM winter"},
        ],
        "important_tips": [
            "Red sandstone facade sunset mein bahut sundar lagta hai.",
            "Monkeys se careful rahein.",
            "History lovers ke liye must-visit stop hai.",
        ],
        "aliases": ["Govind Dev Temple", "Shri Govind Dev Ji Temple"],
    },
    {
        "name": "Pagal Baba Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Mathura-Vrindavan Marg, Vrindavan",
        "famous_for": "10-storey white marble temple with diorama-style displays.",
        "history": "Pagal Baba ke naam se prasiddh sant se judi seva tradition.",
        "main_deity": "Radha Krishna and multiple deities",
        "best_time_to_visit": "Morning 8:00 AM - 11:00 AM",
        "best_season": "October to March",
        "crowd_level": "Low-Medium",
        "average_visit_duration": "45-60 minutes",
        "photography_policy": "Allowed in most areas",
        "dress_code": "Modest",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Prem Mandir", "ISKCON Temple"],
        "parking_info": "Enough parking",
        "google_map_keyword": "Pagal Baba Temple Vrindavan",
        "local_market_food": "Small stalls near entrance",
        "timings": [
            {"session": "Morning Darshan", "timing": "5:00 AM - 11:30 AM summer / 6:00 AM - 12:00 PM winter"},
            {"session": "Evening Darshan", "timing": "3:00 PM - 9:00 PM summer / 3:30 PM - 8:30 PM winter"},
            {"session": "Sandhya Aarti", "timing": "Around 6:30 PM summer / 6:00 PM winter"},
        ],
        "important_tips": [
            "Kids ke saath visit ke liye achha option hai.",
            "Upper floors se panoramic view milta hai.",
            "Prem Mandir route ke saath combine kar sakte hain.",
        ],
        "aliases": ["Shri Pagal Baba Temple"],
    },
    {
        "name": "Shahji Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Near Nidhivan, Vrindavan",
        "famous_for": "Spiral columns, Belgian chandeliers, Basanti Kamra.",
        "history": "19th century temple built by Shah Kundan Lal family.",
        "main_deity": "Chhote Radha Raman",
        "best_time_to_visit": "Morning 8:00 AM - 10:00 AM",
        "best_season": "October to March",
        "crowd_level": "Low",
        "average_visit_duration": "30-45 minutes",
        "photography_policy": "Limited, ask before clicking",
        "dress_code": "Modest",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Nidhivan", "Banke Bihari Temple", "Radha Vallabh Temple"],
        "parking_info": "Very limited",
        "google_map_keyword": "Shahji Temple Vrindavan",
        "local_market_food": "Shops near Nidhivan entrance",
        "timings": [
            {"session": "Morning Darshan", "timing": "8:00 AM - 11:00 AM"},
            {"session": "Evening Darshan", "timing": "5:30 PM - 7:30 PM"},
            {"session": "Shayan Aarti", "timing": "Around 7:15 PM"},
        ],
        "important_tips": [
            "Approach road narrow hai; walking best rahegi.",
            "Architecture aur Basanti Kamra ke liye time rakhein.",
            "Quiet photography etiquette maintain karein.",
        ],
        "aliases": ["Shah Ji Temple"],
    },
    {
        "name": "Madan Mohan Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Near Kaliya Ghat, Dwadashaditya hill, Vrindavan",
        "famous_for": "Vrindavan ke oldest temples mein se ek aur Yamuna-side heritage view.",
        "history": "16th century heritage site with strong early Braj temple lineage.",
        "main_deity": "Madan Mohan Ji",
        "best_time_to_visit": "Morning",
        "best_season": "October to March",
        "crowd_level": "Low",
        "average_visit_duration": "30-40 minutes",
        "photography_policy": "Not allowed inside",
        "dress_code": "Traditional",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Kaliya Ghat", "Yamuna River", "Govind Dev Ji Temple"],
        "parking_info": "Limited",
        "google_map_keyword": "Madan Mohan Temple Vrindavan",
        "local_market_food": "No major market nearby",
        "timings": [
            {"session": "Morning Darshan", "timing": "6:00 AM - 11:00 AM summer / 7:00 AM - 12:00 PM winter"},
            {"session": "Evening Darshan", "timing": "5:00 PM - 9:30 PM summer / 4:00 PM - 8:00 PM winter"},
            {"session": "Sandhya Aarti", "timing": "Around 6:30 PM summer / 6:00 PM winter"},
        ],
        "important_tips": [
            "Hill climb ke liye comfortable footwear rakhein.",
            "Monkeys se sambhal kar rahein.",
            "Sunrise ya sunset views achhe milte hain.",
        ],
        "aliases": ["Shri Madan Mohan Temple"],
    },
    {
        "name": "Jaipur Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Kishor Pura, Mathura-Vrindavan Road, Vrindavan",
        "famous_for": "Rajasthani craftsmanship and peaceful darshan environment.",
        "history": "Jaipur royal patronage se 20th century early period temple development.",
        "main_deity": "Radha Madhav Ji",
        "best_time_to_visit": "Early morning",
        "best_season": "October to March",
        "crowd_level": "Low",
        "average_visit_duration": "30-45 minutes",
        "photography_policy": "Allowed in premises",
        "dress_code": "Modest",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Mathura-Vrindavan Road temples"],
        "parking_info": "Available",
        "google_map_keyword": "Jaipur Temple Vrindavan",
        "local_market_food": "Small shops on Mathura-Vrindavan road",
        "timings": [
            {"session": "Mangala Aarti", "timing": "Around 5:00 AM - 5:30 AM"},
            {"session": "Morning Darshan", "timing": "5:00 AM - 12:00 PM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:00 PM summer / till 8:30 PM winter"},
            {"session": "Sandhya Aarti", "timing": "Around 6:30 PM"},
        ],
        "important_tips": [
            "Peaceful darshan ke liye best temples mein se ek.",
            "Families aur senior citizens ko yeh route pasand aata hai.",
            "Photo-friendly outer premises hain.",
        ],
        "aliases": ["Jaipur Mandir Vrindavan"],
    },
    {
        "name": "Seva Kunj",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Kunj Gali, near Radha Vallabh Temple Road, Vrindavan",
        "famous_for": "Raas leela traditions, sacred grove atmosphere, sunset restriction.",
        "history": "Swami Haridas and Braj bhakti lore se deeply linked sacred space.",
        "main_deity": "Radha Krishna sacred grove",
        "best_time_to_visit": "Morning 8:00 AM - 11:00 AM",
        "best_season": "October to March",
        "crowd_level": "Medium",
        "average_visit_duration": "30-45 minutes",
        "photography_policy": "Not allowed",
        "dress_code": "Modest",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Radha Vallabh Temple", "Banke Bihari Temple"],
        "parking_info": "Not available in old lanes",
        "google_map_keyword": "Seva Kunj Vrindavan",
        "local_market_food": "Shops on Kunj Gali",
        "timings": [
            {"session": "Opening", "timing": "5:30 AM"},
            {"session": "Morning Visit", "timing": "8:00 AM - 11:00 AM"},
            {"session": "Evening Visit", "timing": "4:30 PM - 7:30 PM"},
            {"session": "Closing", "timing": "7:30 PM, no entry after sunset"},
        ],
        "important_tips": [
            "Sunset ke baad entry strictly mana hoti hai.",
            "Silence maintain karna zaroori hai.",
            "Old lane access ke liye paidal jaana easy rahega.",
        ],
        "aliases": ["Seva Kunj Vrindavan", "Seva Kunj (Nidhivan)"],
    },
    {
        "name": "Katyayani Peeth",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Bhaktivedanta Swami Marg, Goda Vihar, Vrindavan",
        "famous_for": "Shakti Peeth association and Katyayani worship.",
        "history": "Ancient Devi tradition linked with Braj pilgrimage circuits.",
        "main_deity": "Goddess Katyayani",
        "best_time_to_visit": "Navratri ya morning darshan",
        "best_season": "October to March",
        "crowd_level": "Low",
        "average_visit_duration": "20-30 minutes",
        "photography_policy": "Not allowed",
        "dress_code": "Modest traditional wear",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["ISKCON Temple", "Prem Mandir"],
        "parking_info": "Limited space",
        "google_map_keyword": "Katyayani Peeth Vrindavan",
        "local_market_food": "Near ISKCON area",
        "timings": [
            {"session": "Morning Darshan", "timing": "6:30 AM - 12:30 PM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 8:30 PM"},
            {"session": "Sandhya Aarti", "timing": "Around 6:30 PM"},
        ],
        "important_tips": [
            "Navratri mein special puja hoti hai.",
            "Women devotees specially visit for Katyayani vrat bhav.",
            "Short but spiritually intense stop hai.",
        ],
        "aliases": ["Uma Shakti Peeth", "Katyayani Temple Vrindavan"],
    },
    {
        "name": "Gopeshwar Mahadev Temple",
        "region": "Vrindavan",
        "category": "temple",
        "location_text": "Wanshivat, near Goda Vihar, Vrindavan",
        "famous_for": "Shiva in Gopi shringar tradition during evening.",
        "history": "Legend ke mutabik Shiva ji ne raas leela dekhne ke liye gopi roop dharan kiya.",
        "main_deity": "Gopeshwar Mahadev",
        "best_time_to_visit": "Evening for Gopi shringar",
        "best_season": "October to March",
        "crowd_level": "Low",
        "average_visit_duration": "20-30 minutes",
        "photography_policy": "Not allowed",
        "dress_code": "Modest",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Banke Bihari Temple", "Radha Raman Temple"],
        "parking_info": "Limited",
        "google_map_keyword": "Gopeshwar Mahadev Temple Vrindavan",
        "local_market_food": "Goda Vihar area",
        "timings": [
            {"session": "Mangala Aarti", "timing": "3:30 AM summer / 4:00 AM winter"},
            {"session": "Morning Darshan", "timing": "5:00 AM - 12:00 PM"},
            {"session": "Evening Darshan", "timing": "4:30 PM - 9:30 PM summer / till 9:00 PM winter"},
            {"session": "Gopi Shringar", "timing": "5:00 PM - 9:00 PM"},
        ],
        "important_tips": [
            "Evening Gopi shringar is the main special attraction.",
            "Morning slot Shiv bhav ke liye accha hai.",
            "Yamuna snan ke baad darshan ka local mahatva maana jata hai.",
        ],
        "aliases": ["Gopeshwar Mahadev", "Gopeshwar Temple"],
    },
    {
        "name": "Shri Krishna Janmabhoomi Temple",
        "region": "Mathura",
        "category": "temple",
        "location_text": "Mathura-Deeg Marg, Near Deeg Gate Chouraha, Mathura",
        "famous_for": "Birthplace of Lord Krishna and Garbha Griha prison-cell darshan.",
        "history": "Mathura ka sabse important teerth site, Krishna janmasthan tradition se juda.",
        "main_deity": "Lord Krishna",
        "best_time_to_visit": "Early morning 5:00 AM - 7:00 AM",
        "best_season": "October to March",
        "crowd_level": "Very High",
        "average_visit_duration": "1 - 1.5 hours",
        "photography_policy": "Strictly prohibited; high security zone",
        "dress_code": "Modest; leather items not allowed",
        "entry_fee": "Free",
        "vip_darshan": "Special queue available",
        "nearby_attractions": ["Potra Kund", "Vishram Ghat", "Dwarkadhish Temple"],
        "parking_info": "Designated parking area",
        "google_map_keyword": "Shri Krishna Janmabhoomi Temple Mathura",
        "local_market_food": "Holi Gate market; Mathura peda, kachori",
        "timings": [
            {"session": "Mangala Aarti", "timing": "5:30 AM summer / 6:00 AM winter"},
            {"session": "Morning Darshan", "timing": "5:00 AM - 12:00 PM"},
            {"session": "Afternoon Break", "timing": "12:00 PM - 4:00 PM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:30 PM"},
            {"session": "Evening Aarti", "timing": "6:00 PM"},
        ],
        "important_tips": [
            "No bags, cameras, mobiles, leather items inside.",
            "ID proof carry karna helpful hota hai.",
            "Security checks ke liye extra buffer time rakhein.",
        ],
        "aliases": ["Shri Krishna Janmabhoomi", "Krishna Janmabhoomi", "Janmabhoomi Temple"],
    },
    {
        "name": "Dwarkadhish Temple",
        "region": "Mathura",
        "category": "temple",
        "location_text": "Vishram Ghat, Vishram Bazar, Mathura",
        "famous_for": "Royal darshan and one of Mathura's most vibrant Krishna temples.",
        "history": "19th century temple patronized by merchant families of Mathura.",
        "main_deity": "Dwarkadhish Ji",
        "best_time_to_visit": "Morning aarti or evening darshan",
        "best_season": "October to March",
        "crowd_level": "Very High",
        "average_visit_duration": "45-60 minutes",
        "photography_policy": "Not allowed inside",
        "dress_code": "Traditional preferred",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Vishram Ghat", "Krishna Janmabhoomi", "Potra Kund"],
        "parking_info": "Very limited in old lanes",
        "google_map_keyword": "Dwarkadhish Temple Mathura",
        "local_market_food": "Vishram Bazar; peda, jalebi, rabri",
        "timings": [
            {"session": "Mangala Aarti", "timing": "6:00 AM summer / 6:30 AM winter"},
            {"session": "Morning Darshan", "timing": "6:30 AM - 10:30 AM summer / till 10:00 AM winter"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 7:00 PM summer / 3:30 PM - 6:30 PM winter"},
            {"session": "Sandhya Aarti", "timing": "6:30 PM summer / 6:00 PM winter"},
        ],
        "important_tips": [
            "Subah ka slot usually better hota hai.",
            "Vishram Ghat ke saath paidal combine kiya ja sakta hai.",
            "Festivals par crowd bahut intense hota hai.",
        ],
        "aliases": ["Shri Dwarkadhish Temple"],
    },
    {
        "name": "Vishram Ghat",
        "region": "Mathura",
        "category": "ghat",
        "location_text": "Chhonka Pada, Vishram Bazar, Mathura",
        "famous_for": "Evening Yamuna aarti and Krishna's sacred resting place.",
        "history": "Braj tradition ke mutabik Kans vadh ke baad Krishna yahan vishram karne aaye the.",
        "main_deity": "Sacred Yamuna Ghat",
        "best_time_to_visit": "Evening 6:00 PM - 7:00 PM",
        "best_season": "October to March",
        "crowd_level": "Medium",
        "average_visit_duration": "45-60 minutes",
        "photography_policy": "Allowed",
        "dress_code": "Modest for holy dip",
        "entry_fee": "Free",
        "vip_darshan": "Not applicable",
        "nearby_attractions": ["Dwarkadhish Temple", "Krishna Janmabhoomi", "Kans Qila"],
        "parking_info": "Limited",
        "google_map_keyword": "Vishram Ghat Mathura",
        "local_market_food": "Chaat and kachori stalls near the ghat",
        "timings": [
            {"session": "Morning Aarti", "timing": "7:00 AM summer / 6:45 AM winter"},
            {"session": "Evening Aarti", "timing": "7:00 PM"},
            {"session": "Open Hours", "timing": "5:00 AM - 9:30 PM"},
        ],
        "important_tips": [
            "Evening aarti is the highlight, so reach early.",
            "Boat rides available depending on local conditions.",
            "Sunset photos bahut achhe aate hain.",
        ],
        "aliases": ["Yamuna Aarti Vishram Ghat"],
    },
    {
        "name": "Birla Mandir",
        "region": "Mathura",
        "category": "temple",
        "location_text": "Mathura-Vrindavan Marg, Garravkendra, Mathura",
        "famous_for": "Gita Stambh and calm Lakshmi Narayan temple setting.",
        "history": "Birla family patronage se modern pilgrimage landmark develop hua.",
        "main_deity": "Lakshmi Narayan",
        "best_time_to_visit": "Morning 7:00 AM aarti",
        "best_season": "October to March",
        "crowd_level": "Low-Medium",
        "average_visit_duration": "45-60 minutes",
        "photography_policy": "Allowed in premises",
        "dress_code": "Modest",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Bhuteshwar Mahadev Temple", "Chamunda Devi Temple"],
        "parking_info": "Ample available",
        "google_map_keyword": "Birla Mandir Mathura",
        "local_market_food": "Mathura-Vrindavan road dhabas",
        "timings": [
            {"session": "Morning Darshan", "timing": "5:00 AM - 12:00 PM summer / 5:30 AM - 12:00 PM winter"},
            {"session": "Evening Darshan", "timing": "2:00 PM - 8:00 PM summer / 2:00 PM - 8:30 PM winter"},
            {"session": "Evening Aarti", "timing": "7:00 PM - 8:00 PM"},
        ],
        "important_tips": [
            "Gita Stambh padhne ke liye extra time rakhein.",
            "Peaceful stop for families and senior citizens.",
            "Roadside parking and access relatively easy hai.",
        ],
        "aliases": ["Gita Mandir", "Birla Mandir (Gita Mandir)"],
    },
    {
        "name": "Bhuteshwar Mahadev Temple",
        "region": "Mathura",
        "category": "temple",
        "location_text": "Near Vishram Ghat, Mathura",
        "famous_for": "Ancient Shiva shrine and guardian deity tradition of Mathura.",
        "history": "Very old Shiv temple with strong local devotion, especially on Mondays and Shivratri.",
        "main_deity": "Bhuteshwar Mahadev",
        "best_time_to_visit": "Morning abhishekam time",
        "best_season": "Shravan and October to March",
        "crowd_level": "Medium",
        "average_visit_duration": "30-45 minutes",
        "photography_policy": "Not allowed inside",
        "dress_code": "Modest",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Vishram Ghat", "Krishna Janmabhoomi", "Dwarkadhish Temple"],
        "parking_info": "Limited",
        "google_map_keyword": "Bhuteshwar Mahadev Temple Mathura",
        "local_market_food": "Nearby local chaat stalls",
        "timings": [
            {"session": "Mangala Aarti", "timing": "5:00 AM - 6:00 AM"},
            {"session": "Abhishekam", "timing": "6:00 AM - 11:00 AM"},
            {"session": "Morning Darshan", "timing": "5:00 AM - 12:00 PM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:30 PM"},
            {"session": "Evening Aarti", "timing": "6:30 PM - 7:30 PM"},
        ],
        "important_tips": [
            "Shravan aur Mondays par extra rush hota hai.",
            "Darshan ke baad Vishram Ghat combine karna easy hai.",
            "Rudrabhishek info local counter se mil sakta hai.",
        ],
        "aliases": ["Bhuteshwar Mahadev", "Bhuteshwar Temple"],
    },
    {
        "name": "Raman Reti",
        "region": "Gokul",
        "category": "temple",
        "location_text": "Gokul, Mathura district, Uttar Pradesh",
        "famous_for": "Krishna childhood leela bhumi and peaceful sandy grounds.",
        "history": "Gokul childhood traditions and Raman Bihari darshan se juda site.",
        "main_deity": "Raman Bihari Ji",
        "best_time_to_visit": "Early morning or evening",
        "best_season": "October to March",
        "crowd_level": "Low",
        "average_visit_duration": "45-60 minutes",
        "photography_policy": "Allowed in gardens, not in shrine",
        "dress_code": "Comfortable footwear-friendly clothing",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Nand Bhavan", "Brahmand Ghat"],
        "parking_info": "Available",
        "google_map_keyword": "Raman Reti Gokul",
        "local_market_food": "Small local eateries",
        "timings": [
            {"session": "Mangala Aarti", "timing": "5:30 AM"},
            {"session": "Morning Darshan", "timing": "5:00 AM - 12:00 PM summer / 5:30 AM - 12:00 PM winter"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:00 PM summer / till 8:00 PM winter"},
        ],
        "important_tips": [
            "Easy footwear aur water bottle rakhein.",
            "Children aur peaceful seekers ke liye achha spot hai.",
            "Animals and open sand areas ke liye relaxed pace rakhein.",
        ],
        "aliases": ["Gokul Raman Reti", "Raman Reti Gokul"],
    },
    {
        "name": "Chamunda Devi Temple",
        "region": "Mathura",
        "category": "temple",
        "location_text": "Mathura-Vrindavan Road, near Maa Gayatri Tapobhumi",
        "famous_for": "Shakti worship, yantra puja tradition, Navratri significance.",
        "history": "Ancient Devi tradition associated with Braj region and local devotion.",
        "main_deity": "Goddess Chamunda",
        "best_time_to_visit": "Navratri or morning darshan",
        "best_season": "October to March",
        "crowd_level": "Low",
        "average_visit_duration": "20-30 minutes",
        "photography_policy": "Not allowed",
        "dress_code": "Modest traditional wear",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Birla Mandir", "ISKCON Vrindavan side"],
        "parking_info": "Limited",
        "google_map_keyword": "Chamunda Devi Temple Mathura",
        "local_market_food": "Roadside stalls nearby",
        "timings": [
            {"session": "Mangala Aarti", "timing": "5:30 AM"},
            {"session": "Morning Darshan", "timing": "6:30 AM - 12:00 PM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:00 PM"},
            {"session": "Evening Aarti", "timing": "7:00 PM"},
        ],
        "important_tips": [
            "Navratri period mein special puja hoti hai.",
            "Short spiritual stop for Devi bhakts.",
            "Road access easy but peak days par parking tighter ho sakti hai.",
        ],
        "aliases": ["Chamunda Devi Mathura"],
    },
    {
        "name": "Potra Kund",
        "region": "Mathura",
        "category": "ghat",
        "location_text": "Inside Shri Krishna Janmabhoomi Complex, Mathura",
        "famous_for": "Sacred kund associated with Krishna janma tradition.",
        "history": "Janmabhoomi complex ka spiritually important ancillary site.",
        "main_deity": "Sacred Kund",
        "best_time_to_visit": "During Janmabhoomi visit",
        "best_season": "October to March",
        "crowd_level": "Medium",
        "average_visit_duration": "15-20 minutes",
        "photography_policy": "Outside photography only as per security rules",
        "dress_code": "Modest",
        "entry_fee": "Free",
        "vip_darshan": "Not applicable",
        "nearby_attractions": ["Krishna Janmabhoomi", "Dwarkadhish Temple", "Vishram Ghat"],
        "parking_info": "Use Janmabhoomi parking",
        "google_map_keyword": "Potra Kund Mathura",
        "local_market_food": "Janmabhoomi complex canteen and nearby stalls",
        "timings": [
            {"session": "Open Hours", "timing": "5:00 AM - 12:00 PM, 4:00 PM - 9:30 PM"},
        ],
        "important_tips": [
            "Security restrictions Janmabhoomi complex jaise hi follow karein.",
            "Combined visit plan karna best hai.",
            "Crowd Janmabhoomi timing ke saath vary karta hai.",
        ],
        "aliases": ["Potra Kund Mathura"],
    },
    {
        "name": "Kans Qila",
        "region": "Mathura",
        "category": "heritage",
        "location_text": "Ratankund, Chowk Bazar, Mathura",
        "famous_for": "Historic fort linked with Kansa lore and old Mathura landscape.",
        "history": "Later-era fort site built and modified across historical periods.",
        "main_deity": "Heritage site",
        "best_time_to_visit": "Morning 8:00 AM - 11:00 AM",
        "best_season": "October to March",
        "crowd_level": "Low-Medium",
        "average_visit_duration": "45-60 minutes",
        "photography_policy": "Allowed",
        "dress_code": "Modest comfortable wear",
        "entry_fee": "Free",
        "vip_darshan": "Not applicable",
        "nearby_attractions": ["Vishram Ghat", "Dwarkadhish Temple", "Potra Kund"],
        "parking_info": "Very limited in Chowk Bazar",
        "google_map_keyword": "Kans Qila Mathura",
        "local_market_food": "Chowk Bazar street food",
        "timings": [
            {"session": "Open Hours", "timing": "7:00 AM - 7:00 PM daily"},
        ],
        "important_tips": [
            "Morning ya evening light best photos ke liye achhi hoti hai.",
            "Old city lanes ke liye walking-ready plan rakhein.",
            "Vishram Ghat route ke saath combine kar sakte hain.",
        ],
        "aliases": ["Kansa Qila", "Kans Quila"],
    },
    {
        "name": "Dauji Temple",
        "region": "Baldeo",
        "category": "temple",
        "location_text": "Baldeo, Mathura district, Uttar Pradesh 281204",
        "famous_for": "Lord Balaram temple and Huranga Holi tradition.",
        "history": "Baldeo region ka major Balaram shrine with strong local festival culture.",
        "main_deity": "Dauji Maharaj (Balaram)",
        "best_time_to_visit": "Morning aarti time",
        "best_season": "October to March",
        "crowd_level": "Medium",
        "average_visit_duration": "30-45 minutes",
        "photography_policy": "Not allowed inside",
        "dress_code": "Traditional",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Gokul", "Raman Reti"],
        "parking_info": "Available",
        "google_map_keyword": "Dauji Temple Mathura",
        "local_market_food": "Baldeo town shops",
        "timings": [
            {"session": "Mangala Aarti", "timing": "5:30 AM - 6:00 AM"},
            {"session": "Morning Darshan", "timing": "6:00 AM - 12:00 PM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:00 PM"},
            {"session": "Sandhya Aarti", "timing": "7:00 PM - 7:30 PM"},
        ],
        "important_tips": [
            "Huranga Holi ke time bahut zyada rush hota hai.",
            "Baldeo route ke liye private vehicle ya taxi easy rehti hai.",
            "Mundan ceremonies ke liye famous hai.",
        ],
        "aliases": ["Dauji Maharaj Temple", "Baldeo Temple"],
    },
    {
        "name": "Mahavidya Temple",
        "region": "Mathura",
        "category": "temple",
        "location_text": "Near Ramleela Ground, west Mathura",
        "famous_for": "Mahavidya Devi worship and local wish-fulfillment traditions.",
        "history": "Mathura ki old Devi tradition se juda shrine.",
        "main_deity": "Mahavidya Devi",
        "best_time_to_visit": "Morning 6:30 AM",
        "best_season": "October to March",
        "crowd_level": "Low",
        "average_visit_duration": "20-30 minutes",
        "photography_policy": "Not allowed",
        "dress_code": "Modest traditional wear",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["West Mathura local shrines"],
        "parking_info": "Limited",
        "google_map_keyword": "Mahavidya Temple Mathura",
        "local_market_food": "Local shops in west Mathura",
        "timings": [
            {"session": "Morning Darshan", "timing": "6:00 AM - 11:30 AM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:00 PM"},
            {"session": "Sandhya Aarti", "timing": "Around 6:30 PM"},
        ],
        "important_tips": [
            "Short darshan stop, less crowded than main city temples.",
            "Navratri aur local festival days par extra bhakti atmosphere hota hai.",
            "Local transport se easily cover kiya ja sakta hai.",
        ],
        "aliases": ["Mahavidya Devi Temple", "Ambika Devi Temple Mathura"],
    },
    {
        "name": "Sri Ji Temple Barsana",
        "region": "Barsana",
        "category": "temple",
        "location_text": "Bhanugarh Hill, Barsana, Mathura district",
        "famous_for": "Radha Rani janmasthan and world-famous Lathmar Holi.",
        "history": "Barsana ki central Radha bhakti peeth with long pilgrimage importance.",
        "main_deity": "Shri Radha Rani (Ladli Lal)",
        "best_time_to_visit": "Morning darshan; Radhashtami and Holi season special",
        "best_season": "October to March",
        "crowd_level": "Medium-High",
        "average_visit_duration": "1 - 1.5 hours",
        "photography_policy": "Not allowed inside",
        "dress_code": "Modest, covered shoulders and knees",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Nandgaon", "Kirti Mandir", "Sankari Khor"],
        "parking_info": "Available at hill base",
        "google_map_keyword": "Sri Ji Temple Barsana",
        "local_market_food": "Barsana market; laddoo and peda",
        "timings": [
            {"session": "Mangala Aarti", "timing": "5:00 AM summer / 5:30 AM winter"},
            {"session": "Morning Darshan", "timing": "5:00 AM - 1:30 PM summer / 6:00 AM - 1:00 PM winter"},
            {"session": "Evening Darshan", "timing": "5:00 PM - 9:00 PM"},
            {"session": "Shayan Aarti", "timing": "Around 8:30 PM"},
        ],
        "important_tips": [
            "200 plus stairs ke liye pace manage karein.",
            "Holi season mein extreme crowd expected hota hai.",
            "Barsana ko half-day ya full-day trip ke roop mein plan karein.",
        ],
        "aliases": ["Radha Rani Temple Barsana", "Ladli Ji Temple"],
    },
    {
        "name": "Nand Bhavan",
        "region": "Nandgaon",
        "category": "temple",
        "location_text": "Nandisvara Hill, Nandgaon, Mathura district",
        "famous_for": "Nand Baba, Yashoda and Bal Krishna childhood home tradition.",
        "history": "Nandgaon ki central leela-sthali with strong Krishna bal-leela association.",
        "main_deity": "Nand Baba, Yashoda, Bal Krishna, Balram",
        "best_time_to_visit": "Morning 6:00 AM - 10:00 AM",
        "best_season": "October to March",
        "crowd_level": "Low-Medium",
        "average_visit_duration": "45-60 minutes",
        "photography_policy": "Allowed in premises",
        "dress_code": "Modest",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Barsana", "Govardhan"],
        "parking_info": "Available at hill base",
        "google_map_keyword": "Nand Bhavan Nandgaon",
        "local_market_food": "Small village shops",
        "timings": [
            {"session": "Morning Darshan", "timing": "6:00 AM - 12:00 PM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 8:00 PM"},
            {"session": "Sandhya Aarti", "timing": "Around 6:30 PM"},
        ],
        "important_tips": [
            "Barsana ke saath combined route best hota hai.",
            "Hill access ke liye walking thodi chadhai wali hai.",
            "Monkey presence ke liye belongings secure rakhein.",
        ],
        "aliases": ["Nand Bhavan Nandgaon"],
    },
    {
        "name": "Kokilavan Shani Dev Temple",
        "region": "Kosi Kalan",
        "category": "temple",
        "location_text": "Kosi Kalan, Mathura district",
        "famous_for": "Shani Dev worship and Kokilavan forest setting.",
        "history": "Local tradition ke mutabik Krishna ne yahan koyal roop mein darshan diye.",
        "main_deity": "Shani Dev",
        "best_time_to_visit": "Saturday morning",
        "best_season": "October to March",
        "crowd_level": "Low",
        "average_visit_duration": "30-45 minutes",
        "photography_policy": "Outside photography allowed",
        "dress_code": "Modest; many devotees prefer black on Saturday",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Nandgaon", "Barsana"],
        "parking_info": "Available",
        "google_map_keyword": "Kokilavan Shani Dev Temple Kosi",
        "local_market_food": "Kosi Kalan town shops",
        "timings": [
            {"session": "Morning Darshan", "timing": "5:00 AM - 12:00 PM"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:00 PM"},
            {"session": "Morning Aarti", "timing": "6:00 AM"},
            {"session": "Evening Aarti", "timing": "7:00 PM"},
        ],
        "important_tips": [
            "Saturday ko crowd relatively zyada hota hai.",
            "Mustard oil offering ke local counters available hote hain.",
            "Long-distance route ke liye cab planning better rehti hai.",
        ],
        "aliases": ["Kokilavan Shani Temple", "Shani Dev Temple Kosi"],
    },
    {
        "name": "Govardhan Temple",
        "region": "Govardhan",
        "category": "temple",
        "location_text": "Govardhan, Mathura district, Uttar Pradesh 281502",
        "famous_for": "Giriraj Maharaj darshan and Govardhan Parikrama route.",
        "history": "Govardhan Parvat Krishna lifting leela se juda sabse important Braj pilgrimage circuits mein se ek hai.",
        "main_deity": "Giriraj Maharaj",
        "best_time_to_visit": "Parikrama early morning",
        "best_season": "October to March",
        "crowd_level": "Medium-High",
        "average_visit_duration": "2-3 hours; full parikrama longer",
        "photography_policy": "Allowed",
        "dress_code": "Comfortable walking clothes",
        "entry_fee": "Free",
        "vip_darshan": "Not available",
        "nearby_attractions": ["Radha Kund", "Kusum Sarovar", "Manasi Ganga"],
        "parking_info": "Available at parikrama start points",
        "google_map_keyword": "Govardhan Temple Mathura",
        "local_market_food": "Govardhan town eateries and shops",
        "timings": [
            {"session": "Mangala Aarti", "timing": "4:15 AM summer / around 5:00 AM winter"},
            {"session": "Temple Darshan", "timing": "4:00 AM - 12:00 PM summer / 5:00 AM - 1:00 PM winter"},
            {"session": "Evening Darshan", "timing": "4:00 PM - 9:00 PM summer / 3:00 PM - 8:00 PM winter"},
            {"session": "Giriraj Aarti", "timing": "7:45 PM summer / around 7:00 PM winter"},
        ],
        "important_tips": [
            "21 km full parikrama ke liye early morning best hota hai.",
            "Water, cap, sunscreen aur light bag rakhein.",
            "Govardhan Puja period mein special spiritual experience hota hai but crowd bhi zyada hota hai.",
        ],
        "aliases": ["Govardhan Hill", "Giriraj Ji Temple", "Govardhan Temple (Giriraj Ji)"],
    },
]
